[WIP] enabled cuda 11.8 for DCS image
databricks/containers pull request #129
Opened 2023-07-26 16:47 UTC by ygong1

* the first commit is just copy 11.8 from 11.0

2023-07-31 16:59 UTC, panchalhp-db requested changes

2023-07-31 16:59 UTC, panchalhp-db commented on ubuntu/gpu/README.md
> + We no longer support [`cuda-10.1`](cuda-10.1) and [`cuda-11.0`](cuda-11.0) complatibility with latest databricks runtime.
```suggestion
 We no longer support [`cuda-10.1`](cuda-10.1) and [`cuda-11.0`](cuda-11.0) compatibility with latest databricks runtime.
```

2023-07-31 16:59 UTC, panchalhp-db commented on ubuntu/gpu/README.md
> +* [`gpu-tensorflow`](cuda-11.0/tensorflow) extends `gpu-venv` by creating a conda environment that contains [TensorFlow](https://www.tensorflow.org/).
```suggestion
* [`gpu-tensorflow`](cuda-11.8/tensorflow) extends `gpu-venv` by creating a conda environment that contains [TensorFlow](https://www.tensorflow.org/).
```

2023-07-31 16:59 UTC, panchalhp-db commented on ubuntu/gpu/cuda-11.8/venv/Dockerfile
> +RUN /usr/local/bin/pip3.10 install --no-cache-dir virtualenv==20.16.3 \
Should we use 20.16.7 to be consistent with DBR 14.0? https://github.com/databricks/universe/blob/master/spark/images/base/virtualenv-python/14.x/dbr-virtualenv-python.dockerfile.py#L22

2023-07-31 16:59 UTC, panchalhp-db commented on ubuntu/gpu/cuda-11.8/venv/Dockerfile
> +  ipython==8.10.0 \
Shall we keep the versions the same as the ones we have in 14.0?

2023-07-31 17:05 UTC, ygong1 commented on ubuntu/gpu/cuda-11.0/base/Dockerfile
> +FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04
oh, good catch, this is leaky experiment I did, will revert it back

2023-07-31 17:05 UTC, ygong1 commented on ubuntu/gpu/cuda-11.8/build.sh
> +docker build -t databricksruntime/gpu-tensorflow:cuda11 tensorflow/
good catch

2023-08-01 17:08 UTC, panchalhp-db approved these changes
LGTM. Just a few minor comments.

2023-08-01 17:08 UTC, panchalhp-db commented on ubuntu/gpu/README.md
> +**WARNING**: DCS images which extends [`venv`](cuda-11.8/venv/) need to be paired with DBR 14.x when creating a
```suggestion
```suggestion
**WARNING**: DCS images which extends [`venv`](cuda-11.8/venv/) need to be paired with DBR 14.x when creating a
```
**WARNING**: DCS images which extends [`venv`](cuda-11.8/venv/) need to be paired with DBR 14.0 and above when creating a
```

2023-08-01 17:08 UTC, panchalhp-db commented on ubuntu/gpu/README.md
> +cluster. In order for REPL to launch successfully, the python packages used in the image HAVE to match with python packges used in the paried DBR version. [`venv`](cuda-11.8/venv/) uses version set f
```suggestion
cluster. In order for REPL to launch successfully, the python packages used in the image HAVE to match with python packges used in the paried DBR version. [`venv`](cuda-11.8/venv/) uses version set from DBR 14.0
```

2023-08-01 17:08 UTC, panchalhp-db commented on ubuntu/gpu/cuda-11.8/venv/Dockerfile
> +# Specifies where Spark will look for the python process
```suggestion
# Specifies where Spark will look for the python binary
```

2023-08-01 17:08 UTC, panchalhp-db commented on ubuntu/gpu/cuda-11.8/venv/Dockerfile
> +# Versions are intended to reflect DBR 14.x: https://docs.databricks.com/release-notes/runtime/releases.html
```suggestion
# Versions are intended to reflect DBR 14.0: https://docs.databricks.com/release-notes/runtime/releases.html
```

2023-08-07 16:39 UTC, merged